# Generated by Django 4.2.2 on 2023-08-25 20:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=0.5,
                size=[300, 500],
                upload_to="tickets_img",
            ),
        ),
    ]
