# Generated by Django 4.2.2 on 2023-08-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
