# Generated by Django 4.2.2 on 2023-08-27 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_userfollows_restrict_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfollows",
            name="restrict_user",
        ),
        migrations.AddField(
            model_name="user",
            name="restrict_user",
            field=models.ManyToManyField(
                blank=True, related_name="restricted_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
